services:
  homassy.api:
    build:
      target: final
      args:
        BUILD_CONFIGURATION: Release
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  homassy.web:
    build:
      target: production
    environment:
      - NODE_ENV=production
    command: node .output/server/index.mjs
    volumes: []  # Remove development volume mounts for production
