name: homassy-web-only

services:
  homassy.web:
    container_name: homassy-web
    image: ${DOCKER_REGISTRY-}homassyweb
    build:
      context: ./Homassy.Web
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NUXT_PUBLIC_API_BASE=${NUXT_PUBLIC_API_BASE:-http://10.0.0.250:5226}
    volumes:
      - ./Homassy.Web:/app
      - /app/node_modules
      - /app/.nuxt
    command: npm run dev -- --host 0.0.0.0
